[package]
name = "swusearch"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
log = "0.4.22"
wasm-bindgen = "0.2.95"
wasm-logger = "0.2.0"
web-sys = "0.3.72"
